name: Maven Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Maven debug mode
        required: false
        default: false
      ssh:
        type: boolean
        description: Open SSH session in the runner
        required: false
        default: false
        
jobs:
  build:
    uses: metricshub/workflows/.github/workflows/maven-build.yml@v2
    with:
      jdkVersion: "17"
      debug: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
      ssh: ${{ github.event_name == 'workflow_dispatch' && inputs.ssh }}
